// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Token struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Blacklisted sql.NullBool   `json:"blacklisted"`
	Token       sql.NullString `json:"token"`
	Type        sql.NullInt32  `json:"type"`
	Expires     time.Time      `json:"expires"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Name      string    `json:"name"`
	Avatar    string    `json:"avatar"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
